#Resource Icon, 1, "drive.ico"
#Resource Manifest, 1, "UNCFromMapped.exe.manifest"

#Resource VersionInfo
#Resource FileVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0
#Resource ProductVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0

#Resource StringInfo "0407", "04B0"

#Resource Version$ "CompanyName",      "BasicAware"
#Resource Version$ "FileDescription",  "Determine UNC path from mapped drive"
#Resource Version$ "LegalCopyright",   "Copyright 2013-2019 BasicAware"
#Resource Version$ "OriginalFilename", "UNCFromMappedDrive.exe"
#Resource Version$ "ProductName",      "UNCFromMappedDrive"
#Resource Version$ "ProductVersion",   "1.0.3.0"
#Resource Version$ "FileVersion",      "1.0.3.0"
#Resource Version$ "Comments",         "Written by Knuth Konrad"

$COMPANY_NAME = "BasicAware"
